plugins {
    id 'com.android.library'
}

android {
    namespace 'com.example.screendaemon'
    compileSdk 34

    defaultConfig {
        minSdk 26
        targetSdk 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

// Tarea para convertir las clases a formato DEX y empaquetar el ScreenDaemon.jar en assets
task buildDaemonJar {
    dependsOn 'compileDebugJavaWithJavac'
    
    doLast {
        def assetsDir = file("${project.rootDir}/app/src/main/assets")
        if (!assetsDir.exists()) {
            assetsDir.mkdirs()
        }

        // Obtener la ruta del SDK de Android directamente desde Gradle
        def sdkDir = android.sdkDirectory.path
        def d8Executable = "${sdkDir}/build-tools/34.0.0/d8"
        
        // En Windows añade extensión .bat si aplica
        if (System.getProperty('os.name').toLowerCase().contains('windows')) {
            d8Executable += ".bat"
        }

        def classFile = file("${buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes/com/example/detectcamera/ScreenDaemon.class")
        def outputJar = file("${assetsDir}/ScreenDaemon.jar")

        if (classFile.exists()) {
            exec {
                commandLine d8Executable, '--output', outputJar.absolutePath, classFile.absolutePath
            }
            println "ScreenDaemon.jar generado exitosamente en: ${outputJar.absolutePath}"
        } else {
            throw new GradleException("No se encontró el archivo compilado ScreenDaemon.class en: ${classFile.absolutePath}")
        }
    }
}

project(':app').tasks.preBuild.dependsOn buildDaemonJar
